# Generated by Django 4.2 on 2023-07-19 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About', max_length=50, unique=True)),
                ('qaot_1', models.TextField()),
                ('sub_title', models.CharField(max_length=200)),
                ('sub_qaot', models.TextField()),
                ('qaot_2', models.TextField()),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('website', models.URLField()),
                ('degree', models.CharField(choices=[('Master', 'Master')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('freelance', models.CharField(default='Available', max_length=50)),
                ('is_chosen', models.BooleanField(default=False, unique=True)),
                ('twitter_id', models.CharField(default='#', max_length=30)),
                ('facebook_id', models.CharField(default='#', max_length=30)),
                ('instagram_id', models.CharField(default='#', max_length=30)),
                ('skype_id', models.CharField(default='#', max_length=30)),
                ('linkedin_id', models.CharField(default='#', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='certs/%Y/%m/%d/')),
                ('institution', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('background_image', models.ImageField(upload_to='background/%Y/%m/%d/')),
                ('fixed_test', models.TextField(blank=True, default="I'm")),
                ('typing_text', models.TextField(blank=True, default='Data scientist, Web Developer, Freelancer')),
                ('is_chosen', models.BooleanField(default=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('duration', models.CharField(default='2020-2023', max_length=50)),
                ('institution', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Skill', max_length=50, unique=True)),
                ('qaot_1', models.TextField()),
                ('skill_1', models.CharField(blank=True, max_length=25)),
                ('skill_1_level', models.IntegerField(blank=True)),
                ('skill_2', models.CharField(blank=True, max_length=25)),
                ('skill_2_level', models.IntegerField(blank=True)),
                ('skill_3', models.CharField(blank=True, max_length=25)),
                ('skill_3_level', models.IntegerField(blank=True)),
                ('skill_4', models.CharField(blank=True, max_length=25)),
                ('skill_4_level', models.IntegerField(blank=True)),
                ('skill_5', models.CharField(blank=True, max_length=25)),
                ('skill_5_level', models.IntegerField(blank=True)),
                ('skill_6', models.CharField(blank=True, max_length=25)),
                ('skill_6_level', models.IntegerField(blank=True)),
                ('skill_7', models.CharField(blank=True, max_length=25)),
                ('skill_7_level', models.IntegerField(blank=True)),
                ('skill_8', models.CharField(blank=True, max_length=25)),
                ('skill_8_level', models.IntegerField(blank=True)),
                ('is_chosen', models.BooleanField(default=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('avatar', models.ImageField(upload_to='profile/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
