# Generated by Django 4.2 on 2023-07-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile/default.png', upload_to='profile/%Y/%m/%d/'),
        ),
    ]
