# Generated by Django 4.2 on 2023-07-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_skill_skill_1_alter_skill_skill_1_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='fixed_test',
            new_name='fixed_text',
        ),
    ]
