# Generated by Django 4.2 on 2023-07-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_fixed_test_main_fixed_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_1_level',
            new_name='skill_level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='is_chosen',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='qaot_1',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_2_level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_3_level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_4_level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_5',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_5_level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_6',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_6_level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_7',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_7_level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_8',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_8_level',
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
