# Generated by Django 4.2 on 2023-07-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_resume_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='column',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], max_length=10, null=True),
        ),
    ]
