# Generated by Django 4.2 on 2023-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_resume_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='column',
            field=models.BooleanField(choices=[(True, 'Left'), (False, 'Right')], default=True),
        ),
    ]
