# Generated by Django 4.2 on 2023-07-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_resume_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='column',
        ),
    ]
