# Generated by Django 4.2 on 2023-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_certification_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='verification_link',
            field=models.URLField(blank=True),
        ),
    ]
