# Generated by Django 4.2 on 2023-07-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_certification_verification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='verification_link',
            field=models.URLField(default='#'),
        ),
    ]
