# Generated by Django 4.2 on 2023-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_certification_verification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='verification_link',
            field=models.CharField(default='#', max_length=250),
        ),
    ]
