# Generated by Django 4.2 on 2023-07-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_certification_verification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='designer',
            field=models.CharField(default='Alibaghban.ir', max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='site_name',
            field=models.CharField(default='mysite.ir', max_length=100),
        ),
    ]
