# Generated by Django 4.2 on 2023-07-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_main_designer_main_site_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='designer',
            new_name='designed_by',
        ),
    ]
