# Generated by Django 4.2 on 2023-07-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_designer_main_designed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='designed_by_link',
            field=models.CharField(default='https://alibaghban.ir', max_length=100),
        ),
    ]
