# Generated by Django 4.2 on 2023-07-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_main_designed_by_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='background/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='main',
            name='favicon_apple',
            field=models.ImageField(blank=True, upload_to='background/%Y/%m/%d/'),
        ),
    ]
