# Generated by Django 4.2 on 2023-07-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_main_favicon_main_favicon_apple'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(default='profile/default.png', upload_to='profile/%Y/%m/%d/'),
        ),
    ]
