# Generated by Django 4.2 on 2023-07-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_about_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_chosen',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
