# Generated by Django 4.2 on 2023-07-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_profile_is_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_chosen',
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
